services:
  - type: web
    name: wastl-proxy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python proxy.py
    plan: free
    envVars:
      - key: PORT
        value: 10000
